

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta do Spring
      - "15672:15672" # Porta da interface web
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"


  db:
    image: postgres:15
    container_name: db_contabil
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: app_contabil
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network: