spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:AppPass#2025}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

  flyway:
    enabled: true
    create-schemas: true
    schemas: RM559755
    baseline-on-migrate: true
    baseline-version: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.fiap.financecontrol: DEBUG
    logging:
      level:
        org:
          flywaydb=info:
          hibernate.SQL: OFF
          hibernate.orm.jdbc.bind: OFF
          hibernate.type.descriptor.sql: OFF